apiVersion: v1
kind: Pod
metadata:
  name: nginx-react
  labels:
    app: nginx-react
spec:
  containers:
    - name: nginx-react
      image: kelseyhightower/nginx-react
      args:
        - "-http=0.0.0.0:80"
        - "-health=0.0.0.0:81"
        - "-secret=secret"
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"