# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  subtree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - run: tree
      - run: git push https://github.com/mermaid-pirates/mermaid-backend.git `git subtree split --prefix backend -b tmp`--force
      - run: git branch -D tmp
      - run: git push https://github.com/mermaid-pirates/mermaid-frontend.git `git subtree split --prefix frontend master`--force
      - run: git branch -D tmp
      
